Section "Device"
    Identifier  "AMD Integrated GPU"
    Driver      "amdgpu"
    BusID       "PCI:122:0:0"
    Option      "TearFree"    "true"
    Option      "DRI"         "3"
EndSection

Section "Screen"
    Identifier  "Default Screen"
    Device      "AMD Integrated GPU"
EndSection
