[Unit]
After=network-online.target nordvpnd.service
Wants=network-online.target nordvpnd.service

[Service]
# Give the interface a few seconds to breathe before starting
ExecStartPre=/usr/bin/sleep 5
Restart=on-failure
RestartSec=10
