#! /bin/sh

# init default display configuration
#xrandr --setprovideroutputsource modesetting NVIDIA-0
dbus-update-activation-environment --all

feh --bg-fill ~/Pictures/wallpapers/cyberpunk.jpg

# set keyboar layout to us int.
setxkbmap us -variant intl

# intialize polkit authentication agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# init sxhkd and compton
pgrep -x sxhkd > /dev/null || sxhkd &

picom &

xss-lock -- /usr/bin/slimlock &

bspc monitor eDP1 -d I II III IV V VI VII VIII IX X

bspc config border_width          2
bspc config window_gap            7

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc rule -a 'Gimp-2.10' desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a vlc state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a guvcview state=floating
bspc rule -a NordPass state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Inkscape desktop='^9' state=floating follow=on rectangle=1600x1000+920+220

$HOME/.config/polybar/launch.sh &

sleep 5
which rog-control-center > /dev/null 2>&1 && pgrep -f rog-control-center > /dev/null || rog-control-center &
