#! /bin/sh
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --output DP-1 --primary --mode 1920x1080 --rotate normal --output DP-3 --mode 1920x1080 --rotate normal --right-of DP-1

setxkbmap us -variant intl

pgrep -x sxhkd > /dev/null || sxhkd &
compton &

bspc monitor DP-1 -d I II III IV V
bspc monitor DP-3 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh

nitrogen --restore &
