#! /bin/sh

# init default display configuration
#xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --output DP-0 --primary --mode 3440x1440 --rate 144.00 --rotate normal # --output HDMI-0 --mode 3440x1440 --rotate normal --left-of DP-0

feh --bg-fill ~/Pictures/wallpapers/cyberpunk.jpg

# set keyboar layout to us int.
setxkbmap us -variant intl

# intialize polkit authentication agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# init sxhkd and compton
pgrep -x sxhkd > /dev/null || sxhkd &
picom &

bspc monitor DP-0 -d I II III IV V VI VII VIII IX X

bspc config border_width          2
bspc config window_gap            7

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
